version: '3.3'

services:
  php:
    image: lehungio/php-fpm:7.1
    volumes:
        - ./:/code

  php_test:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ".:/code"

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "6000:80"
      - "6001:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
