version: '3.3'

services:
  php_test:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ".:/code"

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "38086:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
