# TODO version 3.8
version: '3.7'

services:
  php:
    container_name: php-build
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ".:/code"

  nginx:
    container_name: nginx-image
    image: nginx:latest
    ports:
      - "38086:38086"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf